[package]
name = "rusttype"
version = "0.2.3"
authors = [
    "Dylan Ede <dylanede@googlemail.com>",
    "Jeremy Soller <jackpot51@gmail.com>"
]
description = """
A pure Rust alternative to libraries like FreeType.

RustType provides an API for loading, querying and rasterising TrueType fonts.

It also provides an implementation of a dynamic GPU glyph cache for hardware font rendering.
"""
documentation = "https://docs.rs/rusttype"
homepage = "https://github.com/redox-os/rusttype"
repository = "https://github.com/redox-os/rusttype"
readme = "README.md"
license = "MIT / Apache-2.0"
keywords = ["font", "truetype", "opentype", "ttf", "otf"]
exclude = ["/fonts/**"]

[dependencies]
arrayvec = "0.4"
stb_truetype = "0.2"
linked-hash-map = "0.5"
ordered-float = "0.5"

[dev-dependencies]
glium = "0.17"
unicode-normalization = "0.1"

[features]
# Compiles benchmark code, to be avoided normally as this currently requires nightly rust
bench = []
